apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cloudwash-6hc8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloudwash-6hc8
    app.kubernetes.io/part-of: cloudwash
  name: cloudwash-6hc8
  namespace: psrna-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: cloudwash-6hc8
    weight: null
status: {}
